name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container: swift:latest
    steps:
    - uses: actions/checkout@v5
    - run: swift build --build-tests
    - run: swift test --skip-build --enable-swift-testing --parallel
