name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: swift:6.2
    steps:
    - uses: actions/checkout@v5
    - run: swift build --build-tests
    - run: swift test --skip-build --enable-swift-testing --parallel
